name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d38a9c82d078eacf9930ca60a9c43561d8de258387b20240f4892aea507c0390"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
