plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.54'
}
version = '0.1.0'
group = 'site.siredvin.corruptedstoneblock'
base { archivesName = 'corrupted-stoneblock-worldgen' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        server {
            workingDirectory project.file('run')
            args '--nogui'
            mods { corruptedstoneblock { source sourceSets.main } }
        }
    }
}
repositories {
    mavenCentral()
    maven { url = 'https://www.cursemaven.com' }
}
sourceSets {
    validation {
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += output + compileClasspath
    }
}
tasks.register('validationJar', Jar) {
    archiveClassifier = 'validation'
    from sourceSets.validation.output
}
reobf { validationJar {} }
dependencies {
    validationCompileOnly fg.deobf('curse.maven:ftb-team-bases-1197857:7880652')
    validationCompileOnly fg.deobf('curse.maven:ftb-teams-404468:7499810')
    validationCompileOnly fg.deobf('curse.maven:ftb-library-404465:8226927')
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.named('test', Test) { useJUnitPlatform() }
tasks.named('jar', Jar) { finalizedBy 'reobfJar' }
tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
tasks.register('installPack', Copy) {
    dependsOn 'reobfJar'
    from tasks.named('jar')
    into '../mods'
}
