modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="csbvalidation"
version="0.1.0"
displayName="Corrupted Stoneblock validation (TEST ONLY)"
[[dependencies.csbvalidation]]
modId="corruptedstoneblockcore"
mandatory=true
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.csbvalidation]]
modId="ftbteambases"
mandatory=true
versionRange="[20.1.3,)"
ordering="AFTER"
side="BOTH"
